default:
    paths:
        features: '../features/single'
        bootstrap:  '../features/bootstrap'
    context:
        parameters:
            browserstack:
                server: "hub-cloud.browserstack.com"
                user: "mayankmaurya4"
                key: "JzJJjes3cyzHaynTqJpe"

                capabilities:
                    build: "behat-browserstack"
                    name: "single_test"
                    "browserstack.debug": true

                environments:
                    -
                        browser: "chrome"
